# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RxFMDBManager' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'FMDB'
    pod 'SVProgressHUD'
  # Pods for RxFMDBManager

  target 'RxFMDBManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxFMDBManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
